apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
  labels:
    app: project-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-alpha
  template:
    metadata:
      labels:
        app: project-alpha
    spec:
      containers:
        - name: cont1
          image: 239359658537.dkr.ecr.ap-southeast-1.amazonaws.com/project-alpha:87-d9651e6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"
